### ISSUE TITLE
Is this dead?

### ISSUE THREAD

**Issue by internalfx** [ccampo133/regrid#1]
Trying to determine if this `npm` package name is still in use....

I would like to publish under the name `regrid`.

Trying to contact the maintainer before reaching out to npm.

New project here: https://github.com/internalfx/regrid

**Comment by ccampo133** [comment]
Of course it's in use. It's just a single function, and doesn't have a ton of downloads, but I'm not about to change the name and mess up peoples dependencies. Sorry, but please find another name.

**Comment by internalfx** [comment]
It's not as obvious as you presume.....I was trying to be considerate...

```
$ npm-dependents regrid
regrid has 0 modules depending on it
```

**Comment by ccampo133** [comment]
Oh well, I'd prefer to keep the name. Whether or not published modules have dependencies, other people who have unpublished code may be using it, for whatever reason. Sorry, please find another name.

**Comment by internalfx** [comment]
ReGrid is a storage system for RethinkDB encompassing multiple languages. There is already a C# driver. I am spearheading the JavaScript one. Changing the name now would be quite inconvenient.

I will publish under the name `rethinkdb-regrid`.

**Comment by ccampo133** [comment]
Works for me. Thanks.
